version: '3'

services:
  djangoserver:
    container_name: Ecommerce
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: postgresEcommerce
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: stores
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redisEcommerce
    ports:
      - "6379:6379"

  celery:
    container_name: celeryEcommerce
    build: .
    command: celery -A src worker -l INFO
    restart: always 
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP=True

volumes:
  postgres_data: