# Generated by Django 5.1.3 on 2024-12-22 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_order_id_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='UV17Vr71', max_length=8, unique=True),
        ),
        migrations.CreateModel(
            name='OrderPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_phone', models.CharField(max_length=11)),
                ('pay_image', models.ImageField(upload_to='vodafone_cash')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
